# Create user add ssh_key vault
---
- hosts: "all"
  gather_facts: yes
  become: true
  tasks:
  - name: Create user user1
    ansible.builtin.user:
      name: user1
      
      shell: /bin/bash
      uid: 1111
      
      
      password_expire_max: 99

  - name: Create sssh_key /home/user1/.ssh/id_rsa.pub
    ansible.builtin.user:
      name: user1
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
