---
- name: install end start mysql
  hosts: 158.160.57.10

  tasks:
  - name: Ensure mysql is at the latest version
    ansible.builtin.apt:
     name: mysql-server 
     state: latest
  - name: Ensure that postgresql is started
    ansible.builtin.service:
      name: mysql
      state: started
  
       
